### ISSUE TITLE
Publish token issue

### ISSUE THREAD

**Issue by khisan** [Tonpad/bug-tracker#2] opened 2024-05-03 06:42 UTC
![image](https://github.com/Tonpad/bug-tracker/assets/22789979/6a6307d8-84c1-47da-a385-2ec57e85eccc)
got an error when publish new token on tonlaunch feature
my adress wallet on tonpad : 0QDed_Ap9pxdo28PxTR8p8ThyOQI3j-peBL4ZgK1XWRzA84Z

**Comment by 0xvictorb** [comment] 2024-05-03 07:25
@khisan, thank you for submitting the issue. Could you please provide more information on how you configured the Launchpad? Token information, pool configuration, presale information,..

**Comment by khisan** [comment] 2024-05-03 09:08
This is the detail, i'll try send the image
Token Information: 
![image](https://github.com/Tonpad/bug-tracker/assets/22789979/1de776a0-6bf7-4872-bfe6-6e7b6dd89180)
Pool Configuration: 
![image](https://github.com/Tonpad/bug-tracker/assets/22789979/6e2d98b2-4f9f-4f0f-bc4c-7319718b9820)
Presale Information:
![image](https://github.com/Tonpad/bug-tracker/assets/22789979/cab5cd47-256c-4161-9db7-6b7496666aba)

**Comment by 0xvictorb** [comment] 2024-05-03 12:22
@khisan Thank you so much for letting us know. 
We've looked into the issue and found that the problem is caused by the listing price being too high. Our team is already working on a fix. 
In the meantime, you can try to create a launchpad by reducing the listing price to a smaller value, ex: 1 TON.

We'll let you know again when the bug is fixed.

**Comment by khisan** [comment] 2024-05-03 12:46
@0xvictorb 
thanks for the fix, it work smoothly now

**Comment by khisan** [comment] 2024-05-03 12:53
@0xvictorb thanks, for now i've try reduce the listing price and nothing see any error

**Comment by 0xvictorb** [comment] 2024-05-08 09:27
@khisan this bug has been fixed, I'll close this issue. Feel free to re-open it if you encountered this issue again.

**Closed as completed by 0xvictorb** 2024-05-08 09:27 UTC
