### ISSUE TITLE
an error occured when trying to publish the project

### ISSUE THREAD

**Issue by kalief23** [Tonpad/bug-tracker#7] opened 2024-05-12 15:30 UTC
**Describe the bug**
Error happen when I try to Publish the project, I've assure too that the token I used for creating project is not token that already published, and error message appear when I try to publish my project. FYI , lot of my published project before that become UNKWN token too

**Your Wallet Address**
**Mainnet Wallet:** UQAO-iZktAjzGjZUu_o5Zi2GWirkyh5zMR1aYraw4MK_LeY8
**Testnet Wallet:** 0QAO-iZktAjzGjZUu_o5Zi2GWirkyh5zMR1aYraw4MK_LV22

**Test Environment**
- Device: [Xiaomi Redmi Note 10]
 - OS: [MIUI 14]
 - Wallet name: [Tonkeeper]
 - Environment [Chrome web mobile app (android)]
 - Version [124]

**To Reproduce**
1. Clicked Publish after fill out all necessary information for creating project
2. Scan fingerprint for confirming transaction
3. "an error occured" mesage appear and failed to publish

**Expected behavior**
The error is running nice and smooth again

**Screenshots**
![Screenshot_2024-05-12-22-03-54-135_com ton_keeper](https://github.com/Tonpad/bug-tracker/assets/158295251/ed628c19-3256-4623-b812-9f442e1b8135)
![Screenshot_2024-05-12-22-02-55-092_com ton_keeper](https://github.com/Tonpad/bug-tracker/assets/158295251/7166d8b1-a9e4-4a58-a7c7-a466060bc563)

**Additional context**
- N/A

**Comment by 0xvictorb** [comment] 2024-05-13 03:26
@kalief23
Thanks for the report, the issue is likely due to the TON Testnet being unstable.
I think everything is fine now, could you try to create Launchpad again and see if it works?

**Comment by kalief23** [comment] 2024-05-13 06:32
https://github.com/Tonpad/bug-tracker/assets/158295251/347e763d-c27b-4621-b12e-992a6782a726

Now error is little bit differnt, I try confirm and input password over and over, but transaction never execute

**Comment by 0xvictorb** [comment] 2024-05-13 09:52
@kalief23 That is wallet issue. We'll contact Tonkeeper team and let you know when it resolve.

**Comment by kalief23** [comment] 2024-05-13 11:03
Nice sir, thanks for your kindness 🙏

**Comment by 0xvictorb** [comment] 2024-05-14 15:08
@kalief23 I think everything works well now, please check it again

**Comment by kalief23** [comment] 2024-05-14 16:38
Yes sir, everything works properly now, thanks for your help

**Comment by 0xvictorb** [comment] 2024-05-14 17:13
Thank you for the confirmation, glad it works. I'll close the issue, feel free to reopen if it happens again.

**Closed as completed by 0xvictorb** 2024-05-14 17:13 UTC
